name: CraftyUtils
version: '${version}'
main: xyz.crafttogether.craftyutils.CraftyUtils
api-version: 1.18
depend:
  - CraftCore
commands:
  spawn:
    description: Teleport you back to spawn
    usage: /<command>